### ISSUE TITLE
Can this packages be used in Windows?

### ISSUE THREAD

**Issue by eric-Rstats** [stephenslab/rss#4]
Dear Xiang Zhu：
       I am now using the matlab in Windows,I folllow the steps in installation,but there occurs error like this:
```
 >> run install.m
使用 'Microsoft Visual C++ 2013 Professional (C)' 编译。
错误使用 mex
vectorops.c
E:\rss\src_vb\C\vectorops.c(38) : error C2059: syntax error : 'type'



出错 install (line 24)
eval(['mex ',options,'C/rss_varbvsr_update_matlab.c ',corefiles{1:5}]);

出错 run (line 63)
evalin('caller', [script ';']);
```
Since I already have VS 2013, I am puzzled about this error; Perhaps this package can only be used in Linux?

Best Wishes!

Eric

**Comment by pcarbo** [comment]
Hi Eric, have you compiled MEX files before on your computer? If not, I recommend first setting up the MEX-file compilation. You need to make sure that you have the compiler that is compatible with your version of MATLAB. See here for more info:

http://www.mathworks.com/help/matlab/write-cc-mex-files.html
http://www.mathworks.com/help/matlab/matlab_external/introducing-mex-files.html
http://www.mathworks.com/support/sysreq/previous_releases.html

Peter

**Comment by xiangzhu** [comment]
Dear Eric (@eric-Rstats), 

Many thanks for trying `rss` software! Sorry for my late reply. I was out of town last week.

We developed and tested `rss` only in Linux. For more details about computing environments, please see this page: https://github.com/stephenslab/rss/wiki/Installation

Unfortunately we never used `rss` in Windows. Based on the error message, I speculate that the main issue here is about MEX-file compilation. Hence, I will start with checking whether you can compile the MEX files in the tutorials given on the MathWorks website, as suggested above by my colleague Peter (@pcarbo).

If Windows is the only available environment for you at this moment, can you please provide a detailed description of your environment? I can try to find a machine with a similar setup, and work on this issue from my side.

Finally, if you are only interested [` rss/src_vb/rss_varbvsr.m`](https://github.com/stephenslab/rss/blob/master/src_vb/rss_varbvsr.m), we have a `R` version of this subroutine. Specifically, my colleague Nick (@CreRecombinase) has created an `R` package for this subroutine and several variants. I guess that installing the `R` package may be much easier in Windows. Let me know if you are interested in this package.

**Comment by xiangzhu** [comment]
@pcarbo  I think what you said above is really a good practice when working with MEX files. I add your comments above to the installation page: https://github.com/stephenslab/rss/wiki/RSS-via-VB

**Comment by pcarbo** [comment]
Great!

**Comment by eric-Rstats** [comment]
Hi! @xiangzhu Thank you for your contribution and reply. I'm sorrry for this late reply! 
I am now using my laptop to reply this message. Since I used the Matlab in the computer in my lab, I am sorry that I can't give you the information of the envirnoment in detail; I have tried an example in the Mathwork to test the Mex files, the webiste is here [http://cn.mathworks.com/help/matlab/matlab_external/build-an-executable-mex-file.html](http://cn.mathworks.com/help/matlab/matlab_external/build-an-executable-mex-file.html).I got the output at last. 

   I have never used mex files before, I will examine the software in the lab this weekend. Therefore, I will give you  more explicit information this weekend. At last, we use R frequently, so I am also interested in the R packages by you and your colleague. 

Thank you for you both!

Best Wishes!

Eric

**Comment by pcarbo** [comment]
Hi Eric, if you have full (non-summary) data, you might consider the [varbvs package for R](https://cran.r-project.org/package=varbvs); Xiang's software is effectively varbvs applied to summary data.

**Comment by eric-Rstats** [comment]
@pcarbo Thank you for your suggestion,but I don't have the full data. 
Best wishes!

Eric

**Comment by xiangzhu** [comment]
Hi Eric @eric-Rstats 

I hope all is well. As I mentioned in a previous reply, my colleague Nick (@CreRecombinase) is leading an `R` package development for `RSS`-related methods (`rssr`). If you still have trouble about installing `rss_varbvsr.m` in Windows, you might find our **pre-release** of `rssr`package helpful.

Specifically, please go to https://github.com/stephenslab/rssr, and do the following:

```r
install.packages('devtools')
devtools::install_github("stephenslab/rssr",ref="v0.1.1-alpha",build_vignettes=TRUE)
vignette("example")
```

The vignette shows that `rssr::rss_varbvsr_naive` and `rss_varbvsr.m` produce the same results. Hence, you can instead use `rssr::rss_varbvsr_naive` in `R` if you are interested in the algorithms behind `rss_varbvsr.m` but cannot get it installed in `Matlab`.

Please note that this is only a **pre-release**. A lot of work should be done before we can safely call it a "release". For example, the documentation is lacking. Please feel free to contact me if you have any relevant question.

We only make the basic algorithms publicly available at this point. We developed several more advanced variants (both in `Matlab` and `R`) for our large-scale analyses, and we will make them public as soon as we submit our manuscripts.

Finally, if you think this pre-release of `rssr` provides a (at least temporary) solution to your problem here, please kindly close this issue at your earliest convenience.

**Comment by eric-Rstats** [comment]
Hi @xiangzhu ， Thank you very much ! You are so kind! I will install the `R` packages, so I will close this isssue.

Have a good day!

Best wishes!

Eric

**Comment by pcarbo** [comment]
Hi Eric, if you have difficulty installing the `rssr` package, please refer to [Issue #5](https://github.com/stephenslab/rssr/issues/5) which may help.
